spring.datasource.url=jdbc:postgresql://ep-sweet-waterfall-ap80of8v-pooler.c-7.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_q4b7TlBSftDC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8081}

# Brevo Mail Configuration
mail.enabled=true

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587

spring.mail.username=b28ef4001@smtp-brevo.com
spring.mail.password=YOUR_NEW_BREVO_SMTP_KEY

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Sender email
spring.mail.properties.from=foodrescue.notifications@gmail.com